# Generated by Django 5.1.6 on 2025-02-11 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_resetpassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpassword",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("e3c280af-2485-4941-994f-c58f4499e934"),
                editable=False,
            ),
        ),
    ]
