# Generated by Django 5.1.6 on 2025-02-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_resetpassword_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpassword",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="resetpassword",
            name="token",
            field=models.CharField(),
        ),
    ]
