# Generated by Django 5.1.6 on 2025-02-23 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productvariant_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Vproducts",
                to="products.variation",
            ),
        ),
    ]
