# Generated by Django 5.1.6 on 2025-02-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productvariant_variation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"ordering": ("created_at",)},
        ),
    ]
