# Generated by Django 5.1.6 on 2025-02-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_cart_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ("quantity",)},
        ),
    ]
